"""Small data models for the MASGuard demo tool."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class EvidenceBundle:
    """Evidence extracted from a failed repository-level repair attempt."""

    trajectory_path: str
    repo_path: str
    log_path: str
    patch_path: str
    issue: str = ""
    tool_calls: list[dict[str, Any]] = field(default_factory=list)
    touched_files: list[str] = field(default_factory=list)
    test_targets: list[str] = field(default_factory=list)
    failure_lines: list[str] = field(default_factory=list)
    stack_trace_files: list[str] = field(default_factory=list)
    patch_added_lines: list[str] = field(default_factory=list)
    patch_removed_lines: list[str] = field(default_factory=list)
    repo_files: list[str] = field(default_factory=list)
    signals: dict[str, bool] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class Diagnosis:
    """A deterministic, evidence-citing failure diagnosis."""

    failure_type: str
    responsible_stage: str
    confidence: str
    rationale: str
    evidence: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class RecoveryPlan:
    """A recovery-control plan for a failed LLM software-engineering agent."""

    action: str
    steps: list[str]
    expected_user: str
    scope_note: str
    requires_human_or_agent_execution: bool = True

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class LLMInsight:
    """Optional natural-language layer generated by an OpenAI-compatible API."""

    provider_called: bool
    model: str
    summary: str
    explanation_line: str
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def path_text(path: Path) -> str:
    return str(path.expanduser().resolve())
