"""Report serialization for MASGuard CLI outputs."""

from __future__ import annotations

import json
import html
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from recoveragent.evidence import build_evidence_graph
from recoveragent.models import Diagnosis, EvidenceBundle, LLMInsight, RecoveryPlan


def build_report(
    bundle: EvidenceBundle,
    diagnosis: Diagnosis,
    plan: RecoveryPlan,
    llm_insight: LLMInsight | None = None,
) -> dict:
    insight = llm_insight or LLMInsight(
        provider_called=False,
        model="",
        summary="No optional LLM insight was requested.",
        explanation_line="Deterministic evidence extraction, diagnosis, and recovery planning are the core tool path.",
    )
    return {
        "schema": "masguard.analysis_report.v2",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "tool": "MASGuard",
        "scope_note": {
            "tool_demo_prototype": True,
            "deterministic_core": True,
            "optional_llm_explanation_called": insight.provider_called,
            "does_not_execute_repair": True,
            "does_not_claim_recovery_success": True,
        },
        "evidence_bundle": bundle.to_dict(),
        "evidence_graph": build_evidence_graph(bundle),
        "diagnosis": diagnosis.to_dict(),
        "recovery_plan": plan.to_dict(),
        "llm_insight": insight.to_dict(),
    }


def write_report(report: dict, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")


def write_html_report(report: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_analysis_html(report), encoding="utf-8")


def build_suite_report(case_reports: list[dict[str, Any]]) -> dict[str, Any]:
    diagnosis_counts: dict[str, int] = {}
    action_counts: dict[str, int] = {}
    cases: list[dict[str, Any]] = []

    for report in case_reports:
        case_id = str(report.get("case_id", "unknown"))
        diagnosis = report["diagnosis"]["failure_type"]
        action = report["recovery_plan"]["action"]
        diagnosis_counts[diagnosis] = diagnosis_counts.get(diagnosis, 0) + 1
        action_counts[action] = action_counts.get(action, 0) + 1
        cases.append(
            {
                "case_id": case_id,
                "issue": report["evidence_bundle"].get("issue", ""),
                "diagnosis": diagnosis,
                "confidence": report["diagnosis"]["confidence"],
                "recovery_action": action,
                "baseline_retry_risk": _baseline_retry_risk(report),
                "evidence": report["diagnosis"].get("evidence", [])[:3],
                "graph_nodes": len(report.get("evidence_graph", {}).get("nodes", [])),
                "graph_edges": len(report.get("evidence_graph", {}).get("edges", [])),
            }
        )

    return {
        "schema": "masguard.demo_suite.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "tool": "MASGuard",
        "case_count": len(case_reports),
        "diagnosis_counts": diagnosis_counts,
        "recovery_action_counts": action_counts,
        "cases": cases,
        "scope_note": {
            "comparison_is_demo_control_flow": True,
            "does_not_run_new_llm_repairs": True,
            "does_not_report_recovery_success_rate": True,
        },
    }


def write_markdown_suite(report: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# MASGuard Demo Suite",
        "",
        "This file is generated by `masguard suite` and summarizes deterministic example cases.",
        "It compares the observed failed-agent state with the recovery action selected by MASGuard.",
        "",
        f"- Cases: {report['case_count']}",
        f"- Diagnosis classes: {', '.join(sorted(report['diagnosis_counts']))}",
        "",
        "| Case | Observed failure | MASGuard diagnosis | Recovery action | Naive retry risk |",
        "| --- | --- | --- | --- | --- |",
    ]
    for case in report["cases"]:
        issue = _markdown_cell(case["issue"] or case["case_id"])
        lines.append(
            "| {case_id} | {issue} | {diagnosis} ({confidence}) | {action} | {risk} |".format(
                case_id=_markdown_cell(case["case_id"]),
                issue=issue,
                diagnosis=_markdown_cell(case["diagnosis"]),
                confidence=_markdown_cell(case["confidence"]),
                action=_markdown_cell(case["recovery_action"]),
                risk=_markdown_cell(case["baseline_retry_risk"]),
            )
        )
    lines.extend(
        [
            "",
            "## Video Narrative",
            "",
            "1. Start with the failed trajectory and show the terminal summary.",
            "2. Open the JSON report and highlight evidence, diagnosis, and recovery plan.",
            "3. Run the suite command and show how different failures map to different recovery controls.",
            "4. Explain that the comparison is against the observed failed run and a naive retry policy; the prototype does not claim a solved patch.",
        ]
    )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_html_suite(report: dict[str, Any], output: Path, snapshot: dict[str, Any] | None = None) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_suite_html(report, snapshot=snapshot or {}), encoding="utf-8")


def _analysis_html(report: dict[str, Any]) -> str:
    diagnosis = report["diagnosis"]
    plan = report["recovery_plan"]
    bundle = report["evidence_bundle"]
    graph = report["evidence_graph"]
    insight = report.get("llm_insight", {})
    node_cards = "\n".join(
        f"<div class='node {html.escape(node['kind'])}'><b>{html.escape(node['label'])}</b>"
        f"<small>{html.escape(node['kind'])}</small><p>{html.escape(node.get('detail', ''))}</p></div>"
        for node in graph.get("nodes", [])
    )
    edges = "\n".join(
        f"<li><code>{html.escape(edge['source'])}</code> -> <code>{html.escape(edge['target'])}</code>: "
        f"{html.escape(edge['label'])}</li>"
        for edge in graph.get("edges", [])
    )
    evidence = "\n".join(f"<li>{html.escape(item)}</li>" for item in diagnosis.get("evidence", []))
    steps = "\n".join(f"<li>{html.escape(item)}</li>" for item in plan.get("steps", []))
    return _page(
        "MASGuard Case Report",
        f"""
        <section class="hero">
          <div>
            <p class="eyebrow">Repository-Level Repair-Agent Failure</p>
            <h1>{html.escape(diagnosis['failure_type'])}</h1>
            <p>{html.escape(diagnosis['rationale'])}</p>
          </div>
          <div class="metric"><span>Recovery action</span><b>{html.escape(plan['action'])}</b></div>
        </section>
        <section class="grid two">
          <div>
            <h2>Input Evidence</h2>
            <p>{html.escape(bundle.get('issue', ''))}</p>
            <ul>{evidence}</ul>
          </div>
          <div>
            <h2>Recovery Plan</h2>
            <ul>{steps}</ul>
            <p class="boundary">{html.escape(plan['scope_note'])}</p>
          </div>
        </section>
        <section>
          <h2>Evidence Graph</h2>
          <div class="nodes">{node_cards}</div>
          <details open><summary>Edges</summary><ul>{edges}</ul></details>
        </section>
        <section>
          <h2>Optional LLM Explanation</h2>
          <p>{html.escape(insight.get('summary', ''))}</p>
          <p class="boundary">{html.escape(insight.get('explanation_line', ''))}</p>
        </section>
        """,
    )


def _suite_html(report: dict[str, Any], snapshot: dict[str, Any]) -> str:
    rows = "\n".join(
        "<tr>"
        f"<td>{html.escape(case['case_id'])}</td>"
        f"<td>{html.escape(case['diagnosis'])}<br><small>{html.escape(case['confidence'])}</small></td>"
        f"<td>{html.escape(case['recovery_action'])}</td>"
        f"<td>{html.escape(case['baseline_retry_risk'])}</td>"
        f"<td>{case.get('graph_nodes', 0)} / {case.get('graph_edges', 0)}</td>"
        "</tr>"
        for case in report.get("cases", [])
    )
    metrics = snapshot.get("metrics", {})
    metric_cards = "\n".join(
        f"<div class='metric'><span>{html.escape(str(key).replace('_', ' '))}</span><b>{html.escape(str(value))}</b></div>"
        for key, value in metrics.items()
    )
    return _page(
        "MASGuard Demo Suite",
        f"""
        <section class="hero">
          <div>
            <p class="eyebrow">Tool Demo Workflow</p>
            <h1>Failed trajectory -> evidence graph -> diagnosis -> recovery control</h1>
            <p>MASGuard is a standalone tool and a plugin interface for repository-level repair agents.</p>
          </div>
          <div class="metric"><span>Demo cases</span><b>{report['case_count']}</b></div>
        </section>
        <section>
          <h2>Demo Suite</h2>
          <table>
            <thead><tr><th>Case</th><th>Diagnosis</th><th>Recovery action</th><th>Naive retry risk</th><th>Graph nodes/edges</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </section>
        <section>
          <h2>MASGuard Experiment Snapshot</h2>
          <div class="metrics">{metric_cards}</div>
          <p class="boundary">{html.escape(snapshot.get('scope_note', ''))}</p>
        </section>
        """,
    )


def _page(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
    :root {{ color-scheme: light; --ink:#17202a; --muted:#5d6d7e; --line:#d7dde5; --bg:#f7f8fa; --panel:#ffffff; --accent:#0b6bcb; --warn:#b54708; }}
    body {{ margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background:var(--bg); color:var(--ink); }}
    main {{ max-width:1120px; margin:0 auto; padding:28px; }}
    section {{ background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:22px; margin:16px 0; }}
    .hero {{ display:grid; grid-template-columns:minmax(0,1fr) 260px; gap:20px; align-items:center; background:#fff; }}
    .eyebrow {{ color:var(--accent); font-size:13px; font-weight:700; text-transform:uppercase; letter-spacing:.04em; margin:0 0 8px; }}
    h1 {{ font-size:30px; line-height:1.14; margin:0 0 10px; }}
    h2 {{ font-size:19px; margin:0 0 12px; }}
    p, li, td, th {{ font-size:14px; line-height:1.5; }}
    .grid.two {{ display:grid; grid-template-columns:1fr 1fr; gap:16px; }}
    .metrics, .nodes {{ display:grid; grid-template-columns:repeat(auto-fit, minmax(190px, 1fr)); gap:12px; }}
    .metric, .node {{ border:1px solid var(--line); border-radius:8px; padding:14px; background:#fbfcfe; }}
    .metric span, .node small {{ display:block; color:var(--muted); font-size:12px; margin-bottom:6px; }}
    .metric b {{ font-size:24px; }}
    .node b {{ display:block; font-size:14px; overflow-wrap:anywhere; }}
    .stack_trace {{ border-left:4px solid #2e86c1; }}
    .patch_file {{ border-left:4px solid #b54708; }}
    .tool {{ border-left:4px solid #1e8449; }}
    .input {{ border-left:4px solid #626567; }}
    .boundary {{ color:var(--warn); font-weight:600; }}
    table {{ width:100%; border-collapse:collapse; }}
    th, td {{ text-align:left; border-bottom:1px solid var(--line); padding:10px; vertical-align:top; }}
    code {{ background:#eef2f6; padding:2px 5px; border-radius:4px; }}
    @media (max-width:760px) {{ main {{ padding:14px; }} .hero, .grid.two {{ grid-template-columns:1fr; }} }}
  </style>
</head>
<body><main>{body}</main></body>
</html>
"""


def _baseline_retry_risk(report: dict[str, Any]) -> str:
    signals = report["evidence_bundle"].get("signals", {})
    failure_type = report["diagnosis"]["failure_type"]
    if failure_type in {"fault_localization_failure", "context_drift_or_repeated_mistake"}:
        return "high: likely to repeat the same misleading context"
    if failure_type in {"environment_or_tool_failure", "validation_target_failure"}:
        return "high: retrying repair before validation wastes budget"
    if signals.get("patch_touches_tests") and not signals.get("patch_touches_source"):
        return "medium: retry may preserve an unsafe patch direction"
    return "unknown: needs more evidence"


def _markdown_cell(value: object) -> str:
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return " ".join(text.split())
